GET http://localhost:4000/user/getuser/1

######
GET http://localhost:4000/user/getusers

#####
POST http://localhost:4000/user/create-user
Content-Type: application/json

{
    "id" : 3,
    "name" : "kiran",
    "age": 24
}

#####
PUT http://localhost:4000/user/update-user
Content-Type: application/json

{
    "id" : 1,
    "name" : "ravi babu",
    "age": 24
}

#####
DELETE http://localhost:4000/user/remove-user/1

#####
GET http://localhost:4000/product/getproducts

#####
GET http://localhost:4000/product/getproduct/1

######
POST http://localhost:4000/product/create-product-async
Content-Type: application/json

{
    "id" : 3,
    "name" : "Monitor",
    "price": 24000
}

#####
PUT http://localhost:4000/product/update-product
Content-Type: application/json

{
    "id" : 1,
    "name" : "ravi cooler",
    "price": 20000
}