GET http://localhost:4000/user/getuser/1

######
GET http://localhost:4000/user/getusers

######
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "username": "Rohan",
    "password": "Rohan"
}

#####
POST http://localhost:4000/user/create-user
Content-Type: application/json

{
    "username": "Kiran",
    "password": "Kiran",
    "email": "kiran@email.com",
    "city": "Hyderabad"
}

#####
PUT http://localhost:4000/user/update-user
Content-Type: application/json

{
    "id" : 1,
    "name" : "ravi babu",
    "age": 24
}

#####
DELETE http://localhost:4000/user/remove-user/3

#####
GET http://localhost:4000/product/getproducts

#####
GET http://localhost:4000/product/getproduct/2

######
POST http://localhost:4000/product/create-product-async
Content-Type: application/json

{
    "id" : 2,
    "name" : "Display",
    "price": 34000
}

#####
PUT http://localhost:4000/product/update-product
Content-Type: application/json

{
    "id" : 3,
    "name" : "Monitor",
    "price": 20000
}

#####
DELETE http://localhost:4000/product/remove-product/2